# Generated by Django 5.1.9 on 2025-08-15 09:45

import adl_cimawebdrops_plugin.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_hourlyobsagg_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CimaWebDropsConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('token_endpoint', models.URLField(max_length=255, verbose_name='Token Endpoint URL')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('api_base_url', models.URLField(max_length=255, verbose_name='API Base URL')),
            ],
            options={
                'verbose_name': 'CIMA Web Drops API Connection',
                'verbose_name_plural': 'CIMA Web Drops API Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='CimaWebDropsStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('cima_station_id', models.CharField(max_length=255, verbose_name='CIMA Station')),
                ('start_date', models.DateTimeField(blank=True, help_text='The date to start collection data for the first collection. Ignored if any data has been collected already for this station', null=True, validators=[adl_cimawebdrops_plugin.validators.validate_start_date], verbose_name='Initial Collection start date')),
            ],
            options={
                'verbose_name': 'CIMA Web Drops Station Link',
                'verbose_name_plural': 'CIMA Web Drops Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='CimaWebDropsStationLinkVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('cima_sensor_info', models.CharField(max_length=255, verbose_name='Cima Sensor')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('cima_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Cima Parameter Unit')),
                ('station_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_cimawebdrops_plugin.cimawebdropsstationlink')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
