SENSOR_CLASS_MAP = {
    "UNKNOWN": "Unknown",
    "PLUVIOMETRO": "Rain gauge",
    "IDROMETRO": "Water level (Hydrometer)",
    "IDROMETRO_PORTATA": "Water discharge (Flow rate)",
    "IDROMETRO_VELOCITA": "Water velocity",
    "NIVOMETRO": "Snow gauge",
    "TERMOMETRO": "Air temperature",
    "IGROMETRO": "Relative humidity",
    "DIREZIONEVENTO": "Wind direction",
    "ANEMOMETRO": "Wind speed",
    "BAROMETRO": "Air pressure (Barometer)",
    "RADIOMETRO": "Solar radiation",
    "UNKNOWN_TYPE": "Unknown type",
    "INVASO": "Reservoir level",
    "TURBINATA": "Turbidity",
    "PLUVIOMETRO_OTT": "Optical rain gauge",
    "PORTATA_PRESA": "Intake flow rate",
    "PORTATA_ENTRANTE_STIMATA": "Estimated incoming flow rate",
    "BATTERIA": "Battery voltage",
    "OZONO": "Ozone concentration",
    "PM10": "Particulate matter PM10",
    "IGROMETRO_SUOLO": "Soil moisture",
    "IGROMETRO_SUOLO_10": "Soil moisture (10 cm depth)",
    "IGROMETRO_SUOLO_20": "Soil moisture (20 cm depth)",
    "IGROMETRO_SUOLO_40": "Soil moisture (40 cm depth)",
    "CO": "Carbon monoxide concentration",
    "NO2": "Nitrogen dioxide concentration",
    "C6H6": "Benzene concentration",
    "TERMOMETRO_INTERNA": "Internal temperature",
    "TEMPERATURA_OZONO": "Ozone temperature",
    "DIREZIONEVENTO_RAFFICA": "Wind gust direction",
    "ANEMOMETRO_RAFFICA": "Wind gust speed",
    "TERMOMETRO_MIN": "Minimum temperature",
    "TERMOMETRO_MAX": "Maximum temperature",
    "FUEL_TEMPERATURE": "Fuel temperature",
    "FUEL_MOISTURE": "Fuel moisture",
    "SOIL_TEMPERATURE": "Soil temperature",
    "IONIZING_RADIATION": "Ionizing radiation",
    "SIGNAL_STRENGTH": "Signal strength",
    "NO": "Nitric oxide concentration"
}
